// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPFinal_ParralMiguel.Context;

#nullable disable

namespace TPFinalParralMiguel.Migrations
{
    [DbContext(typeof(ComandasContext))]
    [Migration("20221007095054_newModelPlato")]
    partial class newModelPlato
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc.1.22426.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidoId"));

                    b.Property<bool>("PedidoPreparado")
                        .HasColumnType("bit")
                        .HasColumnName("pedidoPreparado");

                    b.Property<int>("PedidoUsuarioId")
                        .HasColumnType("int");

                    b.Property<float>("PrecioTotal")
                        .HasColumnType("real")
                        .HasColumnName("precioTotal");

                    b.HasKey("PedidoId");

                    b.HasIndex("PedidoUsuarioId");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Plato", b =>
                {
                    b.Property<int>("PlatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatoId"));

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<string>("PlatoNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombrePlato");

                    b.Property<bool>("PlatoPedido")
                        .HasColumnType("bit")
                        .HasColumnName("platoPedido");

                    b.Property<float>("PlatoPrecio")
                        .HasColumnType("real")
                        .HasColumnName("precioPlato");

                    b.HasKey("PlatoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Platos", (string)null);

                    b.HasData(
                        new
                        {
                            PlatoId = 1,
                            PlatoNombre = "Milanesa con guarnición",
                            PlatoPedido = false,
                            PlatoPrecio = 1500f
                        },
                        new
                        {
                            PlatoId = 2,
                            PlatoNombre = "Plato de pastas",
                            PlatoPedido = false,
                            PlatoPrecio = 1200f
                        },
                        new
                        {
                            PlatoId = 3,
                            PlatoNombre = "Hamburguesa con guarnición",
                            PlatoPedido = false,
                            PlatoPrecio = 1600f
                        },
                        new
                        {
                            PlatoId = 4,
                            PlatoNombre = "Gaseosa linea Pepsi",
                            PlatoPedido = false,
                            PlatoPrecio = 750f
                        });
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Usuario", b =>
                {
                    b.Property<int?>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("UsuarioId"));

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("contrasenia");

                    b.Property<string>("UsuarioMail")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("usuarioMail");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("usuarioNombre");

                    b.Property<string>("UsuarioRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rol");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Contrasenia = "123123",
                            UsuarioMail = "pepe@gmail.com",
                            UsuarioNombre = "Pepe",
                            UsuarioRol = "Admin"
                        },
                        new
                        {
                            UsuarioId = 2,
                            Contrasenia = "456456",
                            UsuarioMail = "luci@gmail.com",
                            UsuarioNombre = "Lucia",
                            UsuarioRol = "SuperAdmin"
                        },
                        new
                        {
                            UsuarioId = 3,
                            Contrasenia = "789789",
                            UsuarioMail = "jose@gmail.com",
                            UsuarioNombre = "Jose",
                            UsuarioRol = "User"
                        });
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Pedido", b =>
                {
                    b.HasOne("TPFinal_ParralMiguel.Models.Usuario", "PedidoUsuario")
                        .WithMany("UsuarioPedidos")
                        .HasForeignKey("PedidoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidoUsuario");
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Plato", b =>
                {
                    b.HasOne("TPFinal_ParralMiguel.Models.Pedido", null)
                        .WithMany("ListaPlatos")
                        .HasForeignKey("PedidoId");
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Pedido", b =>
                {
                    b.Navigation("ListaPlatos");
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioPedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
