// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPFinal_ParralMiguel.Context;

#nullable disable

namespace TPFinalParralMiguel.Migrations
{
    [DbContext(typeof(ComandasContext))]
    [Migration("20221013171603_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc.1.22426.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Pedido", b =>
                {
                    b.Property<string>("PedidoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("PedidoPreparado")
                        .HasColumnType("bit")
                        .HasColumnName("pedidoPreparado");

                    b.Property<int>("PedidoUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("PedidoUsuarioUsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("PrecioTotal")
                        .HasColumnType("real")
                        .HasColumnName("precioTotal");

                    b.HasKey("PedidoId");

                    b.HasIndex("PedidoUsuarioUsuarioId");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Plato", b =>
                {
                    b.Property<string>("PlatoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PedidoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PlatoCantidad")
                        .HasColumnType("int")
                        .HasColumnName("platoCantidad");

                    b.Property<string>("PlatoNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombrePlato");

                    b.Property<float>("PlatoPrecio")
                        .HasColumnType("real")
                        .HasColumnName("precioPlato");

                    b.HasKey("PlatoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Platos", (string)null);

                    b.HasData(
                        new
                        {
                            PlatoId = "4ac051d9-4c5a-4bd0-8010-07a3a442b311",
                            PlatoCantidad = 0,
                            PlatoNombre = "Milanesa con guarnición",
                            PlatoPrecio = 1500f
                        },
                        new
                        {
                            PlatoId = "7a72055d-bef0-4de6-8de3-98a8896c5ed8",
                            PlatoCantidad = 0,
                            PlatoNombre = "Plato de pastas",
                            PlatoPrecio = 1200f
                        },
                        new
                        {
                            PlatoId = "d91546a9-d443-46ee-9149-fe8499911a6d",
                            PlatoCantidad = 0,
                            PlatoNombre = "Hamburguesa con guarnición",
                            PlatoPrecio = 1600f
                        },
                        new
                        {
                            PlatoId = "51194b63-408a-471f-9178-06f0d662d0b6",
                            PlatoCantidad = 0,
                            PlatoNombre = "Gaseosa linea Pepsi",
                            PlatoPrecio = 750f
                        });
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Usuario", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("contrasenia");

                    b.Property<string>("UsuarioMail")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("usuarioMail");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("usuarioNombre");

                    b.Property<string>("UsuarioRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rol");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            UsuarioId = "f12ed565-8ffc-48f8-a103-86cde5743555",
                            Contrasenia = "123",
                            UsuarioMail = "pepe@gmail.com",
                            UsuarioNombre = "Pepe",
                            UsuarioRol = "Admin"
                        },
                        new
                        {
                            UsuarioId = "c21f0e9d-1180-445b-9da8-cbbffcab6312",
                            Contrasenia = "456",
                            UsuarioMail = "luci@gmail.com",
                            UsuarioNombre = "Lucia",
                            UsuarioRol = "SuperAdmin"
                        },
                        new
                        {
                            UsuarioId = "fde20520-bde8-441e-8e8c-1c00766b5f92",
                            Contrasenia = "789",
                            UsuarioMail = "jose@gmail.com",
                            UsuarioNombre = "Jose",
                            UsuarioRol = "User"
                        });
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Pedido", b =>
                {
                    b.HasOne("TPFinal_ParralMiguel.Models.Usuario", "PedidoUsuario")
                        .WithMany("UsuarioPedidos")
                        .HasForeignKey("PedidoUsuarioUsuarioId");

                    b.Navigation("PedidoUsuario");
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Plato", b =>
                {
                    b.HasOne("TPFinal_ParralMiguel.Models.Pedido", null)
                        .WithMany("ListaPlatos")
                        .HasForeignKey("PedidoId");
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Pedido", b =>
                {
                    b.Navigation("ListaPlatos");
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioPedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
