// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPFinal_ParralMiguel.Context;

#nullable disable

namespace TPFinalParralMiguel.Migrations
{
    [DbContext(typeof(ComandasContext))]
    [Migration("20221005224329_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc.1.22426.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidoId"));

                    b.Property<bool>("PedidoPreparado")
                        .HasColumnType("bit");

                    b.Property<int>("PedidoUsuarioId")
                        .HasColumnType("int");

                    b.Property<float>("PrecioTotal")
                        .HasColumnType("real");

                    b.HasKey("PedidoId");

                    b.HasIndex("PedidoUsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Plato", b =>
                {
                    b.Property<int>("PlatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatoId"));

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<string>("PlatoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PlatoPrecio")
                        .HasColumnType("real");

                    b.HasKey("PlatoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Platos");
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Usuario", b =>
                {
                    b.Property<int?>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("UsuarioId"));

                    b.Property<string>("Contrasenia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Pedido", b =>
                {
                    b.HasOne("TPFinal_ParralMiguel.Models.Usuario", "PedidoUsuario")
                        .WithMany("UsuarioPedidos")
                        .HasForeignKey("PedidoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidoUsuario");
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Plato", b =>
                {
                    b.HasOne("TPFinal_ParralMiguel.Models.Pedido", null)
                        .WithMany("ListaPlatos")
                        .HasForeignKey("PedidoId");
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Pedido", b =>
                {
                    b.Navigation("ListaPlatos");
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioPedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
