// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPFinal_ParralMiguel.Context;

#nullable disable

namespace TPFinalParralMiguel.Migrations
{
    [DbContext(typeof(ComandasContext))]
    partial class ComandasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc.1.22426.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Pedido", b =>
                {
                    b.Property<string>("PedidoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("PedidoPreparado")
                        .HasColumnType("bit")
                        .HasColumnName("pedidoPreparado");

                    b.Property<string>("PedidoUsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("pedidoUsuarioId");

                    b.Property<float>("PrecioTotal")
                        .HasColumnType("real")
                        .HasColumnName("precioTotal");

                    b.HasKey("PedidoId");

                    b.HasIndex("PedidoUsuarioId");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Plato", b =>
                {
                    b.Property<string>("PlatoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PedidoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PlatoCantidad")
                        .HasColumnType("int")
                        .HasColumnName("platoCantidad");

                    b.Property<string>("PlatoNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombrePlato");

                    b.Property<float>("PlatoPrecio")
                        .HasColumnType("real")
                        .HasColumnName("precioPlato");

                    b.HasKey("PlatoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Platos", (string)null);

                    b.HasData(
                        new
                        {
                            PlatoId = "eac4a6b1-b9cf-4b63-ad4b-8580aa673f36",
                            PlatoCantidad = 0,
                            PlatoNombre = "Milanesa con guarnición",
                            PlatoPrecio = 1500f
                        },
                        new
                        {
                            PlatoId = "0b15307f-db48-4af5-ba76-9a43e762123a",
                            PlatoCantidad = 0,
                            PlatoNombre = "Plato de pastas",
                            PlatoPrecio = 1200f
                        },
                        new
                        {
                            PlatoId = "8bd50cf5-1bcb-4522-a3d6-d9dc9bd21bf1",
                            PlatoCantidad = 0,
                            PlatoNombre = "Hamburguesa con guarnición",
                            PlatoPrecio = 1600f
                        },
                        new
                        {
                            PlatoId = "474426ff-ab9f-4a95-bc18-1d5f58587ee6",
                            PlatoCantidad = 0,
                            PlatoNombre = "Gaseosa linea Pepsi",
                            PlatoPrecio = 750f
                        });
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Usuario", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("contrasenia");

                    b.Property<string>("UsuarioMail")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("usuarioMail");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("usuarioNombre");

                    b.Property<string>("UsuarioRol")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rol");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            UsuarioId = "cd0c749c-ae91-46b1-8b48-5750f63a32b8",
                            Contrasenia = "123",
                            UsuarioMail = "pepe@gmail.com",
                            UsuarioNombre = "Pepe",
                            UsuarioRol = "Admin"
                        },
                        new
                        {
                            UsuarioId = "a658f080-2ad8-4835-a669-1531910f505b",
                            Contrasenia = "456",
                            UsuarioMail = "luci@gmail.com",
                            UsuarioNombre = "Lucia",
                            UsuarioRol = "SuperAdmin"
                        },
                        new
                        {
                            UsuarioId = "37d0aea7-1bce-49e1-b04d-649aae6dc3dc",
                            Contrasenia = "789",
                            UsuarioMail = "jose@gmail.com",
                            UsuarioNombre = "Jose",
                            UsuarioRol = "User"
                        });
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Pedido", b =>
                {
                    b.HasOne("TPFinal_ParralMiguel.Models.Usuario", "PedidoUsuario")
                        .WithMany("UsuarioPedidos")
                        .HasForeignKey("PedidoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidoUsuario");
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Plato", b =>
                {
                    b.HasOne("TPFinal_ParralMiguel.Models.Pedido", null)
                        .WithMany("ListaPlatos")
                        .HasForeignKey("PedidoId");
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Pedido", b =>
                {
                    b.Navigation("ListaPlatos");
                });

            modelBuilder.Entity("TPFinal_ParralMiguel.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioPedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
